import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../page_components/header";
import { Footer } from "@/page_components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <Header />
                <div className="container">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
