import { Zen_Kaku_Gothic_New } from "next/font/google";

import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../header";
import { Footer } from "@/page_components/footer";
import { getUserInfo } from "@/libs/user";
import { db_festival_id } from "@/libs/db/db.type";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
    weight: "900"
});


export default  async function RootLayout({children, params}: Readonly<{children: React.ReactNode; params: Promise<{festival_id: string}>}>) {
    const userInfo = await getUserInfo();
    const user = userInfo.user;

    const { festival_id } = await params;

    return (
        <html lang="ja">
            <body className={zenKakuGothicNew.className}>
                <Header festival_id={festival_id as db_festival_id} isLoggedIn={!!user} icon={userInfo.icon} />
                <div className="container">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
